// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAATNc7OtHl81fhn_BYCyfD2iiQbDlo0O0',
    appId: '1:97726017770:web:72127dd7a6ca846f9aa793',
    messagingSenderId: '97726017770',
    projectId: 'dotalk-101',
    authDomain: 'dotalk-101.firebaseapp.com',
    storageBucket: 'dotalk-101.appspot.com',
    measurementId: 'G-BWTE15Y1HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vWRu-uiPwEYYIV-MjnA0SQRQXoepvbI',
    appId: '1:97726017770:android:c7a9e12a3ca475629aa793',
    messagingSenderId: '97726017770',
    projectId: 'dotalk-101',
    storageBucket: 'dotalk-101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJTlVpOJFadtl8fGJmbqOopKg2np6TtQ',
    appId: '1:97726017770:ios:650f3cb38a7ca6689aa793',
    messagingSenderId: '97726017770',
    projectId: 'dotalk-101',
    storageBucket: 'dotalk-101.appspot.com',
    iosClientId: '97726017770-6nr406bfl3d5udpm05ltigpulg3v4eph.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotalk',
  );
}
